#!/usr/bin/env python3
"""Manage cross-repo project journal indexes for Codex workflows."""

from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import json
import os
import pathlib
import re
import selectors
import shlex
import signal
import stat
import subprocess
import sys
import time
from collections.abc import Callable
from typing import Any


VALID_STATUSES = ("active", "blocked", "completed", "superseded", "abandoned")
REQUIRED_FIELDS = (
    "id",
    "title",
    "status",
    "created",
    "updated",
    "branch",
    "pr",
    "supersedes",
    "superseded_by",
)
DEFAULT_INDEX = pathlib.PurePosixPath("docs/project_journal/INDEX.md")
JOURNAL_ROOT = pathlib.PurePosixPath("docs/project_journal")
HOOK_NAMES = ("post-merge", "post-checkout", "post-rewrite")
HOOK_BEGIN = "# BEGIN PROJECT-JOURNAL-INDEX"
HOOK_END = "# END PROJECT-JOURNAL-INDEX"
INDEX_GENERATED_LINE = (
    "Generated by `project_journal.py`. Do not edit this local index by hand."
)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
INDEX_OID_RE = re.compile(rb"(?:[0-9a-f]{40}|[0-9a-f]{64})\Z")
INDEX_MODE_RE = re.compile(rb"[0-7]{6}\Z")
REGULAR_INDEX_MODES = {b"100644", b"100755"}
MAX_TRACKED_JOURNAL_INDEX_BYTES = 4 * 1024 * 1024
MAX_TRACKED_JOURNAL_RECORDS = 4096
MAX_TRACKED_JOURNAL_BLOB_BYTES = 1024 * 1024
MAX_TRACKED_JOURNAL_TOTAL_BYTES = 16 * 1024 * 1024
MAX_GIT_STDERR_BYTES = 64 * 1024
GIT_INDEX_SNAPSHOT_TIMEOUT_SECONDS = 10.0
GIT_PROCESS_TERMINATE_GRACE_SECONDS = 0.25
GIT_PROCESS_KILL_DRAIN_SECONDS = 1.0
PROCESS_READ_CHUNK_BYTES = 64 * 1024
GIT_ENV_PASSTHROUGH = (
    "HOME",
    "LANG",
    "LC_ALL",
    "LC_CTYPE",
    "PATH",
    "SYSTEMROOT",
    "TEMP",
    "TMP",
    "TMPDIR",
)
SAFE_GIT_ENV = {
    "GIT_ASKPASS": "",
    "GIT_ATTR_NOSYSTEM": "1",
    "GIT_CONFIG_GLOBAL": os.devnull,
    "GIT_CONFIG_NOSYSTEM": "1",
    "GIT_CONFIG_SYSTEM": os.devnull,
    "GIT_LITERAL_PATHSPECS": "1",
    "GIT_NO_LAZY_FETCH": "1",
    "GIT_NO_REPLACE_OBJECTS": "1",
    "GIT_OPTIONAL_LOCKS": "0",
    "GIT_TERMINAL_PROMPT": "0",
    "GCM_INTERACTIVE": "Never",
    "SSH_ASKPASS": "",
    "SSH_ASKPASS_REQUIRE": "never",
}
SAFE_GIT_CONFIG_ARGS = (
    "-c",
    "core.askPass=",
    "-c",
    f"core.attributesFile={os.devnull}",
    "-c",
    "core.fsmonitor=false",
    "-c",
    f"core.hooksPath={os.devnull}",
    "-c",
    "credential.helper=",
    "-c",
    "credential.interactive=never",
)


class UserError(Exception):
    """A clean user-facing error."""


@dataclasses.dataclass(frozen=True)
class JournalEntry:
    path: pathlib.Path
    rel_path: str
    fields: dict[str, Any]

    @property
    def entry_id(self) -> str:
        return str(self.fields.get("id", "")).strip()

    @property
    def title(self) -> str:
        return str(self.fields.get("title", "")).strip()

    @property
    def status(self) -> str:
        return str(self.fields.get("status", "")).strip()

    @property
    def created(self) -> str:
        return str(self.fields.get("created", "")).strip()

    @property
    def updated(self) -> str:
        return str(self.fields.get("updated", "")).strip()


@dataclasses.dataclass(frozen=True)
class IndexJournalBlob:
    mode: bytes
    oid: str
    raw_path: bytes
    rel_path: str


def _git_environment() -> dict[str, str]:
    env = {key: os.environ[key] for key in GIT_ENV_PASSTHROUGH if key in os.environ}
    env.update(SAFE_GIT_ENV)
    return env


def _git_command(repo: pathlib.Path, *args: str) -> list[str]:
    return [
        "git",
        "--no-pager",
        "--no-optional-locks",
        *SAFE_GIT_CONFIG_ARGS,
        "-C",
        str(repo),
        *args,
    ]


def _run_git(repo: pathlib.Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        _git_command(repo, *args),
        check=False,
        env=_git_environment(),
        stdin=subprocess.DEVNULL,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def _run_git_bytes(
    repo: pathlib.Path, *args: str
) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(
        _git_command(repo, *args),
        check=False,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=_git_environment(),
    )


def _resolve_repo(repo_arg: str) -> pathlib.Path:
    candidate = pathlib.Path(repo_arg).expanduser().resolve()
    result = _run_git(candidate, "rev-parse", "--show-toplevel")
    if result.returncode != 0:
        detail = (
            result.stderr.strip() or result.stdout.strip() or "not a git repository"
        )
        raise UserError(f"{candidate} is not a git repository: {detail}")
    return pathlib.Path(result.stdout.strip()).resolve()


def _git_path(repo: pathlib.Path, rel: str) -> pathlib.Path:
    result = _run_git(repo, "rev-parse", "--git-path", rel)
    if result.returncode != 0:
        detail = (
            result.stderr.strip() or result.stdout.strip() or "git path lookup failed"
        )
        raise UserError(f"failed to resolve git path {rel!r}: {detail}")
    path = pathlib.Path(result.stdout.strip())
    if not path.is_absolute():
        path = repo / path
    return path


def _to_repo_rel(repo: pathlib.Path, path_arg: str) -> str:
    path = pathlib.Path(path_arg)
    if path.is_absolute():
        resolved = path.resolve()
    else:
        resolved = (repo / path).resolve()
    try:
        rel = resolved.relative_to(repo)
    except ValueError as exc:
        raise UserError(
            f"output path must resolve inside the repository: {resolved}"
        ) from exc
    return rel.as_posix()


def _strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "[]":
        return []
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [
            _strip_quotes(part.strip()) for part in inner.split(",") if part.strip()
        ]
    return _strip_quotes(value)


def _parse_frontmatter_text(text: str, label: str) -> dict[str, Any]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise UserError(f"{label}: missing frontmatter")

    end = None
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = index
            break
    if end is None:
        raise UserError(f"{label}: unterminated frontmatter")

    fields: dict[str, Any] = {}
    current_key: str | None = None
    for raw_line in lines[1:end]:
        if not raw_line.strip():
            continue
        if raw_line.startswith((" ", "\t")):
            if current_key is None:
                continue
            stripped = raw_line.strip()
            if stripped.startswith("- "):
                existing = fields.get(current_key)
                if not isinstance(existing, list):
                    existing = []
                    fields[current_key] = existing
                existing.append(_strip_quotes(stripped[2:].strip()))
            continue
        if ":" not in raw_line:
            raise UserError(f"{label}: invalid frontmatter line: {raw_line}")
        key, raw_value = raw_line.split(":", 1)
        key = key.strip()
        if not key:
            raise UserError(f"{label}: empty frontmatter key")
        fields[key] = _parse_scalar(raw_value)
        current_key = key
    return fields


def _parse_frontmatter(path: pathlib.Path) -> dict[str, Any]:
    return _parse_frontmatter_text(
        path.read_text(encoding="utf-8"),
        str(path),
    )


def _as_list(value: Any) -> list[str]:
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return [str(value).strip()]


def _journal_paths(repo: pathlib.Path) -> list[pathlib.Path]:
    root = repo / JOURNAL_ROOT
    if not root.exists():
        return []
    paths: list[pathlib.Path] = []
    for path in root.rglob("*.md"):
        if _is_generated_index(path):
            continue
        paths.append(path)
    return sorted(paths)


def _parse_index_stage_record(
    record: bytes,
    records: dict[bytes, list[tuple[bytes, bytes, bytes]]],
) -> None:
    journal_prefix = JOURNAL_ROOT.as_posix().encode("ascii") + b"/"
    default_index = DEFAULT_INDEX.as_posix().encode("ascii")

    metadata, separator, raw_path = record.partition(b"\t")
    fields = metadata.split(b" ")
    if not separator or not raw_path or len(fields) != 3:
        raise UserError("malformed git ls-files stage record")
    mode, oid, stage = fields
    if not INDEX_MODE_RE.fullmatch(mode):
        raise UserError("malformed git ls-files mode")
    if not INDEX_OID_RE.fullmatch(oid):
        raise UserError("malformed git ls-files object id")
    if stage not in {b"0", b"1", b"2", b"3"}:
        raise UserError("malformed git ls-files stage")
    if not raw_path.startswith(journal_prefix):
        raise UserError("git ls-files returned a path outside the journal root")
    path_parts = raw_path.split(b"/")
    if any(part in {b"", b".", b".."} for part in path_parts):
        raise UserError("git ls-files returned an unsafe journal path")
    if raw_path == default_index or not raw_path.endswith(b".md"):
        return
    records.setdefault(raw_path, []).append((mode, oid, stage))


def _index_journal_blobs_from_records(
    records: dict[bytes, list[tuple[bytes, bytes, bytes]]],
) -> list[IndexJournalBlob]:
    blobs: list[IndexJournalBlob] = []
    for raw_path, path_records in sorted(records.items()):
        if len(path_records) != 1:
            continue
        mode, oid, stage = path_records[0]
        if stage != b"0" or mode not in REGULAR_INDEX_MODES:
            continue
        blobs.append(
            IndexJournalBlob(
                mode=mode,
                oid=oid.decode("ascii"),
                raw_path=raw_path,
                rel_path=os.fsdecode(raw_path),
            )
        )
    return blobs


class _IndexStageStreamParser:
    def __init__(self, *, max_records: int = MAX_TRACKED_JOURNAL_RECORDS) -> None:
        self._max_records = max_records
        self._pending = bytearray()
        self._record_count = 0
        self._records: dict[bytes, list[tuple[bytes, bytes, bytes]]] = {}
        self._blobs: list[IndexJournalBlob] | None = None

    def feed(self, chunk: bytes) -> None:
        if self._blobs is not None:
            raise RuntimeError("cannot feed a finished Git index parser")
        self._pending.extend(chunk)
        consumed = 0
        while True:
            terminator = self._pending.find(0, consumed)
            if terminator < 0:
                break
            record = bytes(self._pending[consumed:terminator])
            consumed = terminator + 1
            if not record:
                continue
            self._record_count += 1
            if self._record_count > self._max_records:
                raise UserError(
                    f"tracked journal index exceeds {self._max_records} records"
                )
            _parse_index_stage_record(record, self._records)
        if consumed:
            del self._pending[:consumed]

    def finish(self) -> None:
        if self._blobs is not None:
            return
        if self._pending:
            raise UserError("malformed git ls-files output: missing NUL terminator")
        self._blobs = _index_journal_blobs_from_records(self._records)

    def blobs(self) -> list[IndexJournalBlob]:
        if self._blobs is None:
            raise RuntimeError("Git index parser has not reached EOF")
        return self._blobs


def _parse_index_journal_blobs(output: bytes) -> list[IndexJournalBlob]:
    if len(output) > MAX_TRACKED_JOURNAL_INDEX_BYTES:
        raise UserError(
            "tracked journal index output exceeds "
            f"{MAX_TRACKED_JOURNAL_INDEX_BYTES} bytes"
        )
    parser = _IndexStageStreamParser()
    parser.feed(output)
    parser.finish()
    return parser.blobs()


def _close_selector_stream(
    selector: selectors.BaseSelector,
    stream: Any,
) -> None:
    try:
        selector.unregister(stream)
    except (KeyError, ValueError):
        pass
    try:
        stream.close()
    except OSError:
        pass


def _discard_selector_output(
    selector: selectors.BaseSelector,
    deadline: float,
) -> None:
    while selector.get_map():
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return
        try:
            events = selector.select(remaining)
        except OSError:
            return
        if not events:
            continue
        for key, _mask in events:
            try:
                chunk = os.read(key.fd, PROCESS_READ_CHUNK_BYTES)
            except BlockingIOError:
                continue
            except OSError:
                chunk = b""
            if not chunk:
                _close_selector_stream(selector, key.fileobj)


def _close_selector(selector: selectors.BaseSelector) -> None:
    for key in list(selector.get_map().values()):
        _close_selector_stream(selector, key.fileobj)
    try:
        selector.close()
    except OSError:
        pass


def _signal_process_group(
    process: subprocess.Popen[bytes],
    sig: int,
) -> None:
    try:
        if os.name == "posix":
            os.killpg(process.pid, sig)
        elif sig == signal.SIGTERM:
            process.terminate()
        else:
            process.kill()
    except OSError:
        pass


def _terminate_process_group_and_reap(
    process: subprocess.Popen[bytes],
    selector: selectors.BaseSelector,
) -> None:
    _signal_process_group(process, signal.SIGTERM)
    terminate_deadline = time.monotonic() + GIT_PROCESS_TERMINATE_GRACE_SECONDS
    _discard_selector_output(selector, terminate_deadline)

    kill_signal = getattr(signal, "SIGKILL", signal.SIGTERM)
    _signal_process_group(process, kill_signal)
    kill_deadline = time.monotonic() + GIT_PROCESS_KILL_DRAIN_SECONDS
    _discard_selector_output(selector, kill_deadline)
    _close_selector(selector)

    try:
        process.wait(timeout=max(0.0, kill_deadline - time.monotonic()))
    except subprocess.TimeoutExpired:
        try:
            process.kill()
            process.wait(timeout=GIT_PROCESS_KILL_DRAIN_SECONDS)
        except (OSError, subprocess.TimeoutExpired):
            pass


def _capture_bounded_process(
    argv: list[str],
    *,
    env: dict[str, str],
    timeout_seconds: float,
    stdout_limit: int,
    stderr_limit: int,
    stdout_feed: Callable[[bytes], None] | None = None,
    stdout_finish: Callable[[], None] | None = None,
    stdout_overflow_error: str,
    stderr_overflow_error: str,
    timeout_error: str,
) -> subprocess.CompletedProcess[bytes]:
    if timeout_seconds <= 0:
        raise ValueError("timeout_seconds must be positive")
    if stdout_limit < 0 or stderr_limit < 0:
        raise ValueError("stream limits must not be negative")

    deadline = time.monotonic() + timeout_seconds
    try:
        selector = selectors.DefaultSelector()
    except OSError as exc:
        raise UserError(f"failed to create Git index snapshot selector: {exc}") from exc
    stdout = bytearray()
    stderr = bytearray()
    stdout_finished = False
    try:
        process = subprocess.Popen(
            argv,
            env=env,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            start_new_session=os.name == "posix",
        )
    except OSError as exc:
        _close_selector(selector)
        raise UserError(f"failed to start Git index snapshot: {exc}") from exc

    try:
        assert process.stdout is not None
        assert process.stderr is not None
        for stream, stream_name in (
            (process.stdout, "stdout"),
            (process.stderr, "stderr"),
        ):
            try:
                os.set_blocking(stream.fileno(), False)
                selector.register(
                    stream,
                    selectors.EVENT_READ,
                    data=stream_name,
                )
            except OSError as exc:
                raise UserError(
                    f"failed to configure Git index snapshot {stream_name}: {exc}"
                ) from exc

        while selector.get_map():
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise UserError(timeout_error)
            try:
                events = selector.select(remaining)
            except OSError as exc:
                raise UserError(
                    f"failed to monitor Git index snapshot streams: {exc}"
                ) from exc
            if not events:
                continue
            for key, _mask in events:
                if time.monotonic() >= deadline:
                    raise UserError(timeout_error)
                target = stdout if key.data == "stdout" else stderr
                limit = stdout_limit if key.data == "stdout" else stderr_limit
                available = limit - len(target)
                read_size = min(PROCESS_READ_CHUNK_BYTES, available + 1)
                try:
                    chunk = os.read(key.fd, read_size)
                except BlockingIOError:
                    continue
                except OSError as exc:
                    raise UserError(
                        f"failed to read Git index snapshot {key.data}: {exc}"
                    ) from exc
                if not chunk:
                    _close_selector_stream(selector, key.fileobj)
                    if key.data == "stdout" and not stdout_finished:
                        if stdout_finish is not None:
                            stdout_finish()
                        stdout_finished = True
                    continue
                if len(chunk) > available:
                    if key.data == "stdout":
                        raise UserError(stdout_overflow_error)
                    raise UserError(stderr_overflow_error)
                if key.data == "stdout" and stdout_feed is not None:
                    stdout_feed(chunk)
                target.extend(chunk)

        if not stdout_finished and stdout_finish is not None:
            stdout_finish()
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise UserError(timeout_error)
        try:
            returncode = process.wait(timeout=remaining)
        except subprocess.TimeoutExpired as exc:
            raise UserError(timeout_error) from exc
    except BaseException:
        _terminate_process_group_and_reap(process, selector)
        raise
    else:
        _close_selector(selector)

    return subprocess.CompletedProcess(
        argv,
        returncode,
        bytes(stdout),
        bytes(stderr),
    )


def _tracked_index_journal_snapshot(
    repo: pathlib.Path,
) -> tuple[bytes, list[IndexJournalBlob]]:
    parser = _IndexStageStreamParser()
    command = _git_command(
        repo,
        "ls-files",
        "--stage",
        "-z",
        "--",
        JOURNAL_ROOT.as_posix(),
    )
    result = _capture_bounded_process(
        command,
        env=_git_environment(),
        timeout_seconds=GIT_INDEX_SNAPSHOT_TIMEOUT_SECONDS,
        stdout_limit=MAX_TRACKED_JOURNAL_INDEX_BYTES,
        stderr_limit=MAX_GIT_STDERR_BYTES,
        stdout_feed=parser.feed,
        stdout_finish=parser.finish,
        stdout_overflow_error=(
            "tracked journal index output exceeds "
            f"{MAX_TRACKED_JOURNAL_INDEX_BYTES} bytes"
        ),
        stderr_overflow_error=(
            f"git ls-files stderr exceeds {MAX_GIT_STDERR_BYTES} bytes"
        ),
        timeout_error=(
            "tracked journal index snapshot timed out after "
            f"{GIT_INDEX_SNAPSHOT_TIMEOUT_SECONDS:g} seconds"
        ),
    )
    if result.returncode != 0:
        detail = (
            result.stderr.decode("utf-8", errors="replace").strip()
            or result.stdout.decode("utf-8", errors="replace").strip()
            or "tracked journal lookup failed"
        )
        raise UserError(f"failed to list tracked journal entries: {detail}")
    return result.stdout, parser.blobs()


def _tracked_index_journal_blobs(repo: pathlib.Path) -> list[IndexJournalBlob]:
    _, blobs = _tracked_index_journal_snapshot(repo)
    return blobs


def _read_index_blob(repo: pathlib.Path, blob: IndexJournalBlob) -> bytes:
    size_result = _run_git_bytes(repo, "cat-file", "-s", blob.oid)
    if size_result.returncode != 0:
        detail = (
            size_result.stderr.decode("utf-8", errors="replace").strip()
            or "object size lookup failed"
        )
        raise UserError(f"{blob.rel_path}: failed to inspect index blob: {detail}")
    raw_size = size_result.stdout.strip()
    if not raw_size.isdigit():
        raise UserError(f"{blob.rel_path}: invalid index blob size")
    size = int(raw_size)
    if size > MAX_TRACKED_JOURNAL_BLOB_BYTES:
        raise UserError(
            f"{blob.rel_path}: index blob exceeds "
            f"{MAX_TRACKED_JOURNAL_BLOB_BYTES} bytes"
        )

    content_result = _run_git_bytes(repo, "cat-file", "blob", blob.oid)
    if content_result.returncode != 0:
        detail = (
            content_result.stderr.decode("utf-8", errors="replace").strip()
            or "blob read failed"
        )
        raise UserError(f"{blob.rel_path}: failed to read index blob: {detail}")
    if len(content_result.stdout) != size:
        raise UserError(f"{blob.rel_path}: index blob size changed while reading")
    return content_result.stdout


def _is_generated_index_blob(content: bytes) -> bool:
    lines = content.splitlines()
    return (
        len(lines) >= 3
        and lines[0] == b"# Project Journal Index"
        and lines[2] == INDEX_GENERATED_LINE.encode("utf-8")
    )


def _is_generated_index(path: pathlib.Path) -> bool:
    try:
        content = path.read_bytes()
    except OSError:
        return False
    return _is_generated_index_blob(content)


def _load_entries_from_paths(
    repo: pathlib.Path, paths: list[pathlib.Path]
) -> tuple[list[JournalEntry], list[str]]:
    entries: list[JournalEntry] = []
    issues: list[str] = []
    for path in paths:
        rel_path = path.relative_to(repo).as_posix()
        try:
            fields = _parse_frontmatter(path)
        except UserError as exc:
            issues.append(str(exc))
            continue
        entries.append(JournalEntry(path=path, rel_path=rel_path, fields=fields))
    issues.extend(_validate_entries(entries))
    return entries, issues


def _load_entries(repo: pathlib.Path) -> tuple[list[JournalEntry], list[str]]:
    return _load_entries_from_paths(repo, _journal_paths(repo))


def _load_entries_from_index(
    repo: pathlib.Path,
) -> tuple[list[JournalEntry], list[str], int]:
    entries: list[JournalEntry] = []
    issues: list[str] = []
    non_generated_count = 0
    total_bytes = 0
    initial_index, blobs = _tracked_index_journal_snapshot(repo)

    for blob in blobs:
        content = _read_index_blob(repo, blob)
        total_bytes += len(content)
        if total_bytes > MAX_TRACKED_JOURNAL_TOTAL_BYTES:
            raise UserError(
                "tracked journal blobs exceed "
                f"{MAX_TRACKED_JOURNAL_TOTAL_BYTES} total bytes"
            )
        if _is_generated_index_blob(content):
            continue

        non_generated_count += 1
        try:
            text = content.decode("utf-8")
        except UnicodeDecodeError:
            issues.append(f"{blob.rel_path}: index blob is not valid UTF-8")
            continue
        try:
            fields = _parse_frontmatter_text(text, blob.rel_path)
        except UserError as exc:
            issues.append(str(exc))
            continue
        entry_path = repo.joinpath(*pathlib.PurePosixPath(blob.rel_path).parts)
        entries.append(
            JournalEntry(
                path=entry_path,
                rel_path=blob.rel_path,
                fields=fields,
            )
        )

    final_index, _ = _tracked_index_journal_snapshot(repo)
    if final_index != initial_index:
        raise UserError("tracked journal Git index changed during validation")

    issues.extend(_validate_entries(entries))
    return entries, issues, non_generated_count


def _tracked_journal_adoption(repo: pathlib.Path) -> dict[str, Any]:
    entries, issues, non_generated_count = _load_entries_from_index(repo)
    invalid_paths = {
        entry.rel_path
        for entry in entries
        if any(issue.startswith(f"{entry.rel_path}:") for issue in issues)
    }
    valid_count = sum(entry.rel_path not in invalid_paths for entry in entries)
    return {
        "tracked_journal_adopted": valid_count > 0,
        "tracked_non_generated_journal_count": non_generated_count,
        "valid_tracked_journal_count": valid_count,
    }


def _validate_date(value: str) -> bool:
    if not DATE_RE.match(value):
        return False
    try:
        dt.date.fromisoformat(value)
    except ValueError:
        return False
    return True


def _validate_entries(entries: list[JournalEntry]) -> list[str]:
    issues: list[str] = []
    ids: dict[str, JournalEntry] = {}
    rel_paths = {entry.rel_path for entry in entries}

    for entry in entries:
        label = entry.rel_path
        for field in REQUIRED_FIELDS:
            if field not in entry.fields:
                issues.append(f"{label}: missing required field {field!r}")

        if not entry.entry_id:
            issues.append(f"{label}: field 'id' must not be empty")
        elif entry.entry_id in ids:
            issues.append(f"{label}: duplicate id {entry.entry_id!r}")
        else:
            ids[entry.entry_id] = entry

        if not entry.title:
            issues.append(f"{label}: field 'title' must not be empty")
        if entry.status not in VALID_STATUSES:
            issues.append(
                f"{label}: invalid status {entry.status!r}; expected one of {', '.join(VALID_STATUSES)}"
            )
        if not entry.created:
            issues.append(f"{label}: field 'created' must not be empty")
        elif not _validate_date(entry.created):
            issues.append(f"{label}: invalid created date {entry.created!r}")
        if not entry.updated:
            issues.append(f"{label}: field 'updated' must not be empty")
        elif not _validate_date(entry.updated):
            issues.append(f"{label}: invalid updated date {entry.updated!r}")

    valid_targets = set(ids) | rel_paths
    for entry in entries:
        for superseded in _as_list(entry.fields.get("supersedes")):
            if superseded not in valid_targets:
                issues.append(
                    f"{entry.rel_path}: supersedes target {superseded!r} does not match a journal id or path"
                )
        target = str(entry.fields.get("superseded_by", "")).strip()
        if target and target not in valid_targets:
            issues.append(
                f"{entry.rel_path}: superseded_by target {target!r} does not match a journal id or path"
            )
        if entry.status == "superseded":
            if not target:
                issues.append(
                    f"{entry.rel_path}: superseded entries must set 'superseded_by'"
                )

    return issues


def _markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _link_from_output(output_path: pathlib.Path, entry: JournalEntry) -> str:
    rel = os.path.relpath(entry.path, start=output_path.parent)
    return pathlib.PurePosixPath(rel).as_posix()


def _entry_sort_key(entry: JournalEntry) -> tuple[str, str, str]:
    return (entry.updated, entry.created, entry.title.lower())


def _render_index(
    repo: pathlib.Path, output_path: pathlib.Path, entries: list[JournalEntry]
) -> str:
    grouped = {status: [] for status in VALID_STATUSES}
    for entry in entries:
        if entry.status in grouped:
            grouped[entry.status].append(entry)
    for values in grouped.values():
        values.sort(key=_entry_sort_key, reverse=True)

    lines = [
        "# Project Journal Index",
        "",
        INDEX_GENERATED_LINE,
        "",
        "## Summary",
        "",
    ]
    for status in VALID_STATUSES:
        lines.append(f"- `{status}`: {len(grouped[status])}")
    lines.append("")

    if not entries:
        lines.extend(["No project journal entries found.", ""])
        return "\n".join(lines)

    for status in VALID_STATUSES:
        lines.extend([f"## {status.title()}", ""])
        if not grouped[status]:
            lines.extend(["_None._", ""])
            continue
        lines.append("| Updated | Title | ID | Branch | PR |")
        lines.append("| --- | --- | --- | --- | --- |")
        for entry in grouped[status]:
            href = _link_from_output(output_path, entry)
            title = _markdown_escape(entry.title)
            branch = _markdown_escape(str(entry.fields.get("branch", "")).strip())
            pr = _markdown_escape(str(entry.fields.get("pr", "")).strip())
            lines.append(
                f"| {entry.updated} | [{title}]({href}) | `{_markdown_escape(entry.entry_id)}` | {branch} | {pr} |"
            )
        lines.append("")
    return "\n".join(lines)


def _ensure_exclude(repo: pathlib.Path, output_rel: str) -> pathlib.Path:
    exclude_path = _git_path(repo, "info/exclude")
    exclude_path.parent.mkdir(parents=True, exist_ok=True)
    existing = exclude_path.read_text(encoding="utf-8") if exclude_path.exists() else ""
    lines = existing.splitlines()
    if output_rel not in lines:
        if existing and not existing.endswith("\n"):
            existing += "\n"
        existing += f"{output_rel}\n"
        exclude_path.write_text(existing, encoding="utf-8")
    return exclude_path


def command_generate(args: argparse.Namespace) -> int:
    repo = _resolve_repo(args.repo)
    output_rel = _to_repo_rel(repo, args.output)
    output_path = repo / output_rel
    entries, issues = _load_entries(repo)
    if issues:
        raise UserError(
            "journal validation failed before index generation:\n" + "\n".join(issues)
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_render_index(repo, output_path, entries), encoding="utf-8")
    if args.ensure_exclude:
        _ensure_exclude(repo, output_rel)
    print(output_path)
    return 0


def command_validate(args: argparse.Namespace) -> int:
    repo = _resolve_repo(args.repo)
    _entries, issues = _load_entries(repo)
    if issues:
        for issue in issues:
            print(issue, file=sys.stderr)
        return 1
    print("Project journal validation passed.")
    return 0


def command_adoption_status(args: argparse.Namespace) -> int:
    repo = _resolve_repo(args.repo)
    status = {"repo": str(repo), **_tracked_journal_adoption(repo)}
    print(json.dumps(status, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


def command_append_hook_log(args: argparse.Namespace) -> int:
    repo = _resolve_repo(args.repo)
    log_path = _git_path(repo, "project-journal-index.log")
    try:
        with log_path.open("ab") as log:
            while chunk := sys.stdin.buffer.read(64 * 1024):
                log.write(chunk)
    except OSError as exc:
        raise UserError(f"failed to append project journal hook log: {exc}") from exc
    return 0


def _hook_body() -> str:
    python_exe = shlex.quote(sys.executable)
    script_path = shlex.quote(str(pathlib.Path(__file__).resolve()))
    return f"""#!/bin/sh
{HOOK_BEGIN}
hook_name=${{0##*/}}
if [ "$hook_name" = "post-rewrite" ] && [ ! -t 0 ]; then
  cat >/dev/null || true
fi

if [ "${{PROJECT_JOURNAL_INDEX_DISABLE:-}}" = "1" ]; then
  exit 0
fi

repo=$(pwd -P 2>/dev/null)
if [ -z "$repo" ]; then
  exit 0
fi

tmp_log=$(mktemp "${{TMPDIR:-/tmp}}/project-journal-index.XXXXXX" 2>/dev/null)

if [ -n "$tmp_log" ]; then
  if ! {{
    date -u '+%Y-%m-%dT%H:%M:%SZ'
    {python_exe} {script_path} generate --repo "$repo" --output {DEFAULT_INDEX.as_posix()} --ensure-exclude
  }} > "$tmp_log" 2>&1; then
    {python_exe} {script_path} _append-hook-log --repo "$repo" < "$tmp_log" 2>/dev/null || true
  fi
  rm -f "$tmp_log"
else
  {python_exe} {script_path} generate --repo "$repo" --output {DEFAULT_INDEX.as_posix()} --ensure-exclude >/dev/null 2>&1 || true
fi

exit 0
{HOOK_END}
"""


def _hooks_dir_from_config(repo: pathlib.Path, raw_path: str) -> pathlib.Path:
    if not raw_path.strip():
        raise UserError(
            "core.hooksPath is empty; unset it or set a non-empty hook directory before installing"
        )
    if raw_path == os.devnull:
        raise UserError(
            "core.hooksPath points at os.devnull; cannot install project journal hooks"
        )
    hooks_dir = pathlib.Path(raw_path).expanduser()
    if not hooks_dir.is_absolute():
        hooks_dir = repo / hooks_dir
    hooks_dir = hooks_dir.resolve()
    allowed_roots = [repo.resolve(), _git_path(repo, ".").resolve()]
    common_dir = _run_git(repo, "rev-parse", "--git-common-dir")
    if common_dir.returncode == 0 and common_dir.stdout.strip():
        common_path = pathlib.Path(common_dir.stdout.strip())
        if not common_path.is_absolute():
            common_path = repo / common_path
        allowed_roots.append(common_path.resolve())
    if not any(_is_relative_to(hooks_dir, root) for root in allowed_roots):
        raise UserError(
            "core.hooksPath resolves outside the repository or git directory; "
            "set a repo-local hook directory before installing"
        )
    return hooks_dir


def _default_hooks_dir(repo: pathlib.Path) -> pathlib.Path:
    common_dir = _run_git(repo, "rev-parse", "--git-common-dir")
    if common_dir.returncode != 0 or not common_dir.stdout.strip():
        detail = (
            common_dir.stderr.strip()
            or common_dir.stdout.strip()
            or "Git common directory lookup failed"
        )
        raise UserError(f"failed to resolve default hook directory: {detail}")
    common_path = pathlib.Path(common_dir.stdout.strip())
    if not common_path.is_absolute():
        common_path = repo / common_path
    hooks_dir = common_path.resolve() / "hooks"
    if hooks_dir.is_symlink():
        raise UserError(
            f"{hooks_dir} is a symlink; refusing to install hooks through hook directory links"
        )
    return hooks_dir.resolve()


def _hooks_dir(repo: pathlib.Path) -> pathlib.Path:
    for scope in ("--worktree", "--local"):
        configured = _run_git(
            repo,
            "config",
            "--includes",
            scope,
            "--get",
            "core.hooksPath",
        )
        if configured.returncode == 0:
            return _hooks_dir_from_config(repo, configured.stdout.strip())
    return _default_hooks_dir(repo)


def _hook_path(repo: pathlib.Path, name: str) -> pathlib.Path:
    return _hooks_dir(repo) / name


def _preflight_hook_targets(repo: pathlib.Path) -> list[pathlib.Path]:
    hook_paths = [_hook_path(repo, name) for name in HOOK_NAMES]
    for hook_path in hook_paths:
        if hook_path.is_symlink():
            raise UserError(
                f"{hook_path} is a symlink; refusing to overwrite hook links"
            )
        if not hook_path.exists():
            continue
        existing = hook_path.read_text(encoding="utf-8", errors="replace")
        if HOOK_BEGIN not in existing or HOOK_END not in existing:
            raise UserError(
                f"{hook_path} already exists and is not managed by project_journal.py"
            )
        before, _marker, rest = existing.partition(HOOK_BEGIN)
        _managed, _end_marker, after = rest.partition(HOOK_END)
        before_lines = [line for line in before.splitlines() if line.strip()]
        if before_lines not in ([], ["#!/bin/sh"]) or after.strip():
            raise UserError(
                f"{hook_path} contains unmanaged content outside the project journal marker block"
            )
    return hook_paths


def _install_hook(hook_path: pathlib.Path) -> pathlib.Path:
    hook_path.parent.mkdir(parents=True, exist_ok=True)
    if hook_path.is_symlink():
        raise UserError(f"{hook_path} is a symlink; refusing to overwrite hook links")
    if hook_path.exists():
        existing = hook_path.read_text(encoding="utf-8", errors="replace")
        if HOOK_BEGIN not in existing or HOOK_END not in existing:
            raise UserError(
                f"{hook_path} already exists and is not managed by project_journal.py"
            )
    hook_path.write_text(_hook_body(), encoding="utf-8")
    mode = hook_path.stat().st_mode
    hook_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return hook_path


def command_install_hooks(args: argparse.Namespace) -> int:
    repo = _resolve_repo(args.repo)
    hook_paths = _preflight_hook_targets(repo)
    _ensure_exclude(repo, DEFAULT_INDEX.as_posix())
    installed = [_install_hook(path) for path in hook_paths]
    for path in installed:
        print(path)
    return 0


def _path_date(path: pathlib.Path) -> dt.date | None:
    parts = path.parts
    for index, part in enumerate(parts):
        if part == "sessions" and index + 3 < len(parts):
            try:
                return dt.date(
                    int(parts[index + 1]),
                    int(parts[index + 2]),
                    int(parts[index + 3]),
                )
            except ValueError:
                continue
    return None


def _rollout_last_seen(path: pathlib.Path) -> str:
    dated = _path_date(path)
    if dated is not None:
        return dated.isoformat()
    mtime = dt.datetime.fromtimestamp(path.stat().st_mtime, tz=dt.timezone.utc)
    return mtime.date().isoformat()


def _rollout_in_window(path: pathlib.Path, cutoff: dt.date) -> bool:
    dated = _path_date(path)
    if dated is not None:
        return dated >= cutoff
    mtime = dt.datetime.fromtimestamp(path.stat().st_mtime, tz=dt.timezone.utc)
    return mtime.date() >= cutoff


def _walk_for_cwds(value: Any) -> list[str]:
    found: list[str] = []
    if isinstance(value, dict):
        for key, item in value.items():
            if key in {
                "cwd",
                "workdir",
                "working_dir",
                "working_directory",
            } and isinstance(item, str):
                found.append(item)
            else:
                found.extend(_walk_for_cwds(item))
    elif isinstance(value, list):
        for item in value:
            found.extend(_walk_for_cwds(item))
    return found


def _extract_cwds(rollout: pathlib.Path) -> list[str]:
    cwds: list[str] = []
    with rollout.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            cwds.extend(_walk_for_cwds(payload))
    return cwds


def _known_source_root_from_temp_path(path: pathlib.Path) -> pathlib.Path | None:
    parts = path.parts
    for index, part in enumerate(parts):
        if part != ".codex-tmp" or index + 2 >= len(parts):
            continue
        temp_name = parts[index + 1]
        workspace_name = parts[index + 2]
        if temp_name.startswith("isolated-review-") and workspace_name == "workspace":
            source = pathlib.Path(*parts[:index])
            return source if source != pathlib.Path() else pathlib.Path("/")
    return None


def _is_relative_to(path: pathlib.Path, parent: pathlib.Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
    except ValueError:
        return False
    return True


def _git_output_path(repo: pathlib.Path, raw_path: str) -> pathlib.Path:
    path = pathlib.Path(raw_path.strip())
    if not path.is_absolute():
        path = repo / path
    return path.resolve()


def _source_root_from_linked_worktree(repo: pathlib.Path) -> pathlib.Path | None:
    git_dir = _run_git(repo, "rev-parse", "--git-dir")
    common_dir = _run_git(repo, "rev-parse", "--git-common-dir")
    if git_dir.returncode != 0 or common_dir.returncode != 0:
        return None

    git_dir_path = _git_output_path(repo, git_dir.stdout)
    common_dir_path = _git_output_path(repo, common_dir.stdout)
    if git_dir_path == common_dir_path:
        return None

    source = (
        common_dir_path.parent if common_dir_path.name == ".git" else common_dir_path
    )
    source_root = _repo_root_for_existing_path(source)
    if source_root is None or source_root == repo:
        return None
    return source_root


def _repo_root_for_existing_path(path: pathlib.Path) -> pathlib.Path | None:
    while not path.exists():
        parent = path.parent
        if parent == path:
            return None
        path = parent
    result = _run_git(path, "rev-parse", "--show-toplevel")
    if result.returncode != 0:
        return None
    return pathlib.Path(result.stdout.strip()).resolve()


def _repo_root_for_path(
    path_text: str, *, codex_home: pathlib.Path | None = None
) -> pathlib.Path | None:
    path = pathlib.Path(path_text).expanduser()
    if not path.is_absolute():
        return None
    source = _known_source_root_from_temp_path(path)
    if source is not None:
        source_root = _repo_root_for_existing_path(source)
        if source_root is not None:
            return source_root
    root = _repo_root_for_existing_path(path)
    if root is None:
        return None
    if codex_home is not None and _is_relative_to(root, codex_home / "worktrees"):
        source_root = _source_root_from_linked_worktree(root)
        if source_root is not None:
            return source_root
    return root


def _unique_preserving_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    unique: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        unique.append(value)
    return unique


def _has_hook_marker(repo: pathlib.Path) -> bool:
    for name in HOOK_NAMES:
        try:
            hook = _hook_path(repo, name)
        except UserError:
            return False
        if not hook.exists():
            return False
        try:
            content = hook.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return False
        if HOOK_BEGIN not in content or HOOK_END not in content:
            return False
    return True


def _is_excluded(repo: pathlib.Path, rel: str) -> bool:
    exclude = _git_path(repo, "info/exclude")
    if not exclude.exists():
        return False
    return rel in exclude.read_text(encoding="utf-8", errors="replace").splitlines()


def _discover_repos(codex_home: pathlib.Path, since_days: int) -> list[dict[str, Any]]:
    sessions = codex_home / "sessions"
    if not sessions.exists():
        return []
    cutoff = (dt.datetime.now(dt.timezone.utc) - dt.timedelta(days=since_days)).date()
    seen: dict[pathlib.Path, dict[str, Any]] = {}
    resolved_roots: dict[str, pathlib.Path | None] = {}
    script = pathlib.Path(__file__).resolve()

    for rollout in sorted(sessions.rglob("rollout-*.jsonl")):
        if not rollout.is_file() or not _rollout_in_window(rollout, cutoff):
            continue
        last_seen = _rollout_last_seen(rollout)
        roots_for_rollout: set[pathlib.Path] = set()
        for cwd in _unique_preserving_order(_extract_cwds(rollout)):
            if cwd not in resolved_roots:
                resolved_roots[cwd] = _repo_root_for_path(cwd, codex_home=codex_home)
            root = resolved_roots[cwd]
            if root is None:
                continue
            roots_for_rollout.add(root)
        for root in roots_for_rollout:
            row = seen.setdefault(
                root,
                {
                    "repo": str(root),
                    "last_seen": last_seen,
                    "rollout_count": 0,
                },
            )
            row["last_seen"] = max(str(row["last_seen"]), last_seen)
            row["rollout_count"] = int(row["rollout_count"]) + 1

    results: list[dict[str, Any]] = []
    for root, row in sorted(seen.items(), key=lambda item: item[0].as_posix()):
        journal_root = root / JOURNAL_ROOT
        index_rel = DEFAULT_INDEX.as_posix()
        adoption = _tracked_journal_adoption(root)
        row.update(
            {
                "has_journal_dir": journal_root.is_dir(),
                "journal_count": len(_journal_paths(root)),
                "has_index": (root / index_rel).is_file(),
                "index_ignored": _is_excluded(root, index_rel),
                "hooks_installed": _has_hook_marker(root),
                "install_command": f"{shlex.quote(sys.executable)} {shlex.quote(str(script))} install-hooks --repo {shlex.quote(str(root))}",
                "generate_command": f"{shlex.quote(sys.executable)} {shlex.quote(str(script))} generate --repo {shlex.quote(str(root))} --output {index_rel} --ensure-exclude",
                **adoption,
            }
        )
        results.append(row)
    return results


def command_discover_repos(args: argparse.Namespace) -> int:
    codex_home = pathlib.Path(args.codex_home).expanduser().resolve()
    rows = _discover_repos(codex_home, args.since_days)
    if args.json_output:
        print(json.dumps(rows, ensure_ascii=False, indent=2, sort_keys=True))
        return 0
    for row in rows:
        print(
            f"{row['repo']}\tlast_seen={row['last_seen']}\t"
            f"journals={row['journal_count']}\thooks={row['hooks_installed']}"
        )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate = subparsers.add_parser(
        "generate", help="Generate a local project journal index."
    )
    generate.add_argument("--repo", required=True)
    generate.add_argument("--output", default=DEFAULT_INDEX.as_posix())
    generate.add_argument("--ensure-exclude", action="store_true")
    generate.set_defaults(func=command_generate)

    validate = subparsers.add_parser(
        "validate", help="Validate project journal frontmatter."
    )
    validate.add_argument("--repo", required=True)
    validate.set_defaults(func=command_validate)

    adoption = subparsers.add_parser(
        "adoption-status",
        help="Report valid tracked journal evidence for adoption checks.",
    )
    adoption.add_argument("--repo", required=True)
    adoption.set_defaults(func=command_adoption_status)

    hook_log = subparsers.add_parser(
        "_append-hook-log",
        help=argparse.SUPPRESS,
    )
    hook_log.add_argument("--repo", required=True)
    hook_log.set_defaults(func=command_append_hook_log)

    hooks = subparsers.add_parser(
        "install-hooks", help="Install local Git hooks for index refresh."
    )
    hooks.add_argument("--repo", required=True)
    hooks.set_defaults(func=command_install_hooks)

    discover = subparsers.add_parser(
        "discover-repos", help="Discover Codex-touched Git repos."
    )
    discover.add_argument(
        "--codex-home",
        default=os.environ.get("CODEX_HOME", "~/.codex"),
        help="Codex home to inspect. Defaults to CODEX_HOME or ~/.codex.",
    )
    discover.add_argument("--since-days", type=int, default=30)
    discover.add_argument("--json", action="store_true", dest="json_output")
    discover.set_defaults(func=command_discover_repos)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except UserError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
